services:
  ipfees.web:    
    image: registry.gitlab.com/vbocan/ipfees:web
    container_name: ipfees-web
    build:
      context: .
      dockerfile: IPFees.Web/Dockerfile    
    env_file:
      - .env
    restart: unless-stopped
    labels:
      # Expose container to Traefik
      - traefik.enable=true
      # Create the RedirectScheme middleware
      - traefik.http.middlewares.salescoach-redirect-websecure.redirectscheme.scheme=https
      - traefik.http.middlewares.salescoach-redirect-websecure.redirectscheme.permanent=true
      - traefik.http.middlewares.salescoach-redirect-websecure.redirectscheme.port=443
      # Create router for HTTP and apply the redirect middleware
      - traefik.http.routers.salescoach-http.rule=Host(`ipfees.dataman.ro`)
      - traefik.http.routers.salescoach-http.middlewares=salescoach-redirect-websecure
      # Create router for HTTPS
      - traefik.http.routers.salescoach-https.rule=Host(`ipfees.dataman.ro`)
      - traefik.http.routers.salescoach-https.entrypoints=websecure
      - traefik.http.routers.salescoach-https.tls=true
      - traefik.http.routers.salescoach-https.tls.certresolver=le
    networks:
      - webhost

  ipfees.api:
    image: registry.gitlab.com/vbocan/ipfees:api
    container_name: ipfees-api
    build:
      context: .
      dockerfile: IPFees.Api/Dockerfile    
    env_file:
      - .env
    restart: unless-stopped
    labels:
      # Expose container to Traefik
      - traefik.enable=true
      # Create the RedirectScheme middleware
      - traefik.http.middlewares.salescoach-redirect-websecure.redirectscheme.scheme=https
      - traefik.http.middlewares.salescoach-redirect-websecure.redirectscheme.permanent=true
      - traefik.http.middlewares.salescoach-redirect-websecure.redirectscheme.port=443
      # Create router for HTTP and apply the redirect middleware
      - traefik.http.routers.salescoach-http.rule=Host(`ipfeesapi.dataman.ro`)
      - traefik.http.routers.salescoach-http.middlewares=salescoach-redirect-websecure
      # Create router for HTTPS
      - traefik.http.routers.salescoach-https.rule=Host(`ipfeesapi.dataman.ro`)
      - traefik.http.routers.salescoach-https.entrypoints=websecure
      - traefik.http.routers.salescoach-https.tls=true
      - traefik.http.routers.salescoach-https.tls.certresolver=le
    networks:
      - webhost
  
networks:
  webhost:
    name: "webhost"
