services:
  ipfees.web:    
    image: registry.gitlab.com/vbocan/ipfees:web
    container_name: ipfees-web
    build:
      context: .
      dockerfile: IPFees.Web/Dockerfile
    restart: unless-stopped
    depends_on:
      - mongodb

  ipfees.api:
    image: registry.gitlab.com/vbocan/ipfees:api
    container_name: ipfees-api
    build:
      context: .
      dockerfile: IPFees.Api/Dockerfile    
    restart: unless-stopped
    depends_on:
      - mongodb
  
  mongodb:
    image: mongo:latest
    container_name: ipfees-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pA$$w0rd
    restart: unless-stopped
    ports:
      - 27017:27017

volumes:
  mongodb_data:
  mongodb_log:
