name: Build and Push Docker Images

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push API image
      uses: docker/build-push-action@v5
      with:
        context: src/
        file: src/IPFees.API/Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/ipfees:api

    - name: Build and push Web image
      uses: docker/build-push-action@v5
      with:
        context: src/
        file: src/IPFees.Web/Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/ipfees:web